### PR TITLE
Fixed reference to the PX4ESC codebase for Pixhawk ESC v1.4

### PR DESCRIPTION
**Pull request by pavel-kirienko**
Fixes issue described at https://github.com/PX4/px4esc/issues/15#issuecomment-170504089

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks!

**Comment by geosmall** [comment]
Documentation page build instruction omits necessary command:

git submodule update --init --recursive

**Comment by LorenzMeier** [comment]
@geosmall Could you send a PR for this? Thanks!

**Comment by pavel-kirienko** [comment]
PR is up: https://github.com/PX4/Devguide/pull/61

**Comment by geosmall** [comment]
Sorry, still learning when to create new PRs.  I see I should have created a PR against the documentation page.  Thanks for fixing!

**Pull request merged**
