### PR TITLE
added documentation for DSP shell (qshell)

### PR DESCRIPTION
**Pull request by ndepal**
@LorenzMeier

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@ndepal Any reason to not make qshell part of the default build and simplify the instructions here?

**Comment by LorenzMeier** [comment]
We prefer automation in general over documentation. More code, less text!

**Comment by ndepal** [comment]
the 3 bullet points are actually part of that PR, I just mentioned it in case somebody plays around with their configs so its easier to figure out all the parts needed. That's why I write 'make sure that this is the case'.

**Comment by LorenzMeier** [comment]
The additional text is confusing. Good documentation has to focus on the essential and its our job to ensure that master and documentation are in sync. We do not guarantee anything except that. People using old software will need to check out old documentation.

**Comment by ndepal** [comment]
I shortened it

**Comment by LorenzMeier** [comment]
Looks great, thanks!

**Pull request merged**
