### PR TITLE
mavros offboard control example

### PR DESCRIPTION
**Pull request by andre-nguyen**
With a bonus .webm of the thing in action :smile:

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice!

**Comment by vooon** [comment]
@andre-nguyen few things need to be fixed:

1. topic/service name: please remove starting `/`: it prevents namespacing (roslaunch `<group ns="">`)
   Also maybe add somewhere note that `mavros/` prefix may be different in some advanced configurations (because all topics are in private namespace `~` which expands as `<node_name>/`, node name may be changed in launch).
2. Before starting operation better to wait connection: `~state` provide that information, also you can check that OFFBOARD is actually enabled.
3. Topic queue_size, 1 is ok, but in ros guides usually 10...
4. One side effect that current ROS Service API is syncronious, so some calls may block for some time (usually mavros timeouts 5-10 sec). Perhaps promises from ROS2 may help to write single-threaded controller nodes, but that is future…


// offtopic: @LorenzMeier as i seen, firmware interprets all mode set requests for main mode only, so i can't request AUTO.RTL, only AUTO.MISSION.
Maybe i should add sanity check on that kind of modes? And second question: should i add RATTITUDE or it is experimental? I only see it in QGC...

**Comment by LorenzMeier** [comment]
Rattitude is fully supported. And I just filed the issue for sub-modes, so they will be supported as well.
https://github.com/PX4/Firmware/issues/3257

I would like to encourage you to *NOT* do special handling, but to work with the flight stack developers to get corner cases fixed.

**Comment by LorenzMeier** [comment]
@vooon Please don't comment in closed issues. I've filed a new one from this.

**Pull request merged**
