### PR TITLE
Added doc for JLink debugger

### PR DESCRIPTION
**Pull request by CarlOlsson**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks! The check failed, most likely an incorrect link. Please check the travis output.

**Comment by CarlOlsson** [comment]
When I run: "gitbook serve book" the devguide looks fine to me in the localhost. 
I have had a look at the travis output but can't narrow down the problem. Could you please have a look at it?

**Comment by CarlOlsson** [comment]
In the travis output there is an error message on line 587. I did not change anything regarding this file so don't know where the error comes from.
travis1

**Comment by LorenzMeier** [comment]
You need to rebase on master to fix this.

**Pull request merged**
