### PR TITLE
Updated Snapdragon Flight HW page

### PR DESCRIPTION
**Pull request by mcharleb**
Signed-off-by: Mark Charlebois <charlebm@gmail.com>

### CODE REVIEW

**Comment by LorenzMeier** [comment]
We commonly mandate the tool chain installation instructions to be on the corresponding page in this documentation set (in fact they are already stubbed out there and just need to be completed) - this change links them out to another Readme. Can we change that to simplify the user experience? We don't want people to have to change through several pages. This is also critical as we might depend on a particular tool chain version.

**Comment by mcharleb** [comment]
Where should the qurt build specific details live?

**Comment by LorenzMeier** [comment]
There is a Hexagon section on that page: http://dev.px4.io/starting-installing-linux.html#

**Comment by mcharleb** [comment]
I moved the toolchain and SDK related info to starting-installing-linux.md

**Comment by LorenzMeier** [comment]
Awesome, thanks!

**Pull request merged**
