### PR TITLE
Streaming video in QGC

### PR DESCRIPTION
**Pull request by fkaiser**
This would be a supplement to the QGC documentation that shows how to set up a system that consists of an Odroid C1, a logitech camera C920 and a WiFi antenna such that this system can be used to stream a video to the QGC that runs on a computer.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
I'm not merging this until we have cleared video format and resolution. Any update there?

**Comment by mhkabir** [comment]
I would suggest 1280x720@30fps default for the guide. It's a good tradeoff between resolution and latency. 

Especially on Android devices, handling anything above 1280x720 creates a great deal of lag, since QGC can't take advantage of the platform's hardware acceleration. 

I've been using a GoPro with the above settings, and I get below 90ms glass to glass latency.

**Comment by fkaiser** [comment]
I have tried all possible resolutions. Taking the lowest available resolution (320x240) is most stable. However, sometimes it is still lagging a little bit.

**Comment by fkaiser** [comment]
Ok Update: Resolution 160x120 also works and looks fine. No lag detected at this resolution
.

**Comment by dogmaphobic** [comment]
I'm not sure what's going on with your tablet. I'm assuming it just doesn't have enough power to render the video. I have no issues with 1080P at 30fps with either Nexus 9 or iPad Air.

Regarding the images in this PR, let me help you with them. I can provide much more detailed images as I have done all of this multiple times.

**Comment by LorenzMeier** [comment]
Rebased and applied.

**Pull request closed without merging**
